from pydantic import BaseModel, Field
from langchain.schema import Document

class RAGState(BaseModel):
    query: str = Field(description="User query or question")
    documents: list[Document] = Field(
        default_factory=list,
        description= "Top reranked document chunks with metadata"
    )
    context: str = Field(
        default="",
        description="Formatted context string passed to the LLM"
    )
    answer: str = Field(
        default="",
        description="Final answer generated by the LLM"
    )
    score: float = Field(
        default=0.0,
        description="Confidence or relevance score for the answer"
    )